### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'input')

### ISSUE THREAD

**Issue by Giovanni-Schroevers** [Code-Hex/graphql-codegen-typescript-validation-schema#386]
```
 TypeError: Cannot read properties of undefined (reading 'input')
        at Visitor.getScalarType (graphcommerce/node_modules/graphql-codegen-typescript-validation-schema/dist/main/visitor.js:30:40)
        at generateFieldTypeZodSchema (graphcommerce/node_modules/graphql-codegen-typescript-validation-schema/dist/main/zod/index.js:146:40)
        at generateFieldTypeZodSchema (graphcommerce/node_modules/graphql-codegen-typescript-validation-schema/dist/main/zod/index.js:135:21)
        at generateFieldTypeZodSchema (graphcommerce/node_modules/graphql-codegen-typescript-validation-schema/dist/main/zod/index.js:126:21)
        at generateFieldTypeZodSchema (graphcommerce/node_modules/graphql-codegen-typescript-validation-schema/dist/main/zod/index.js:135:21)
        at generateFieldZodSchema (graphcommerce/node_modules/graphql-codegen-typescript-validation-schema/dist/main/zod/index.js:121:17)
        at graphcommerce/node_modules/graphql-codegen-typescript-validation-schema/dist/main/zod/index.js:46:103
        at Array.map (<anonymous>)
        at Object.leave (graphcommerce/node_modules/graphql-codegen-typescript-validation-schema/dist/main/zod/index.js:46:90)
        at visit (graphcommerce/node_modules/graphql/language/visitor.js:197:21) {
      source: '../../packagesDev/next-config/src/generated/config.ts'
```

It seems to be a problem with nested input types. To fix the issue the following patch seems to be working:

```patch
diff --git a/node_modules/graphql-codegen-typescript-validation-schema/dist/main/visitor.js b/node_modules/graphql-codegen-typescript-validation-schema/dist/main/visitor.js
index 82da858..f2088f0 100644
--- a/node_modules/graphql-codegen-typescript-validation-schema/dist/main/visitor.js
+++ b/node_modules/graphql-codegen-typescript-validation-schema/dist/main/visitor.js
@@ -26,6 +26,9 @@ class Visitor extends typescript_1.TsVisitor {
         if (this.scalarDirection === 'both') {
             return null;
         }
+        if (!this.scalars[scalarName]) {
+            return null;
+        }
         return this.scalars[scalarName][this.scalarDirection];
     }
 }
```

**Comment by Rigo-m** [comment]
Fix works, but then the types don't get generated correctly

**Comment by Rigo-m** [comment]
Are your scalars something like this? 
```
 export type Scalars = {
  ID: { input: string | number; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  BooleanType: { input: any; output: any; }
  CustomData: { input: any; output: any; }
  DateTime: { input: any; output: any; }
  FloatType: { input: any; output: any; }
  IntType: { input: any; output: any; }
  ItemId: { input: any; output: any; }
  MetaTagAttributes: { input: any; output: any; }
  UploadId: { input: any; output: any; }
};

```

**Comment by Code-Hex** [comment]
@Giovanni-Schroevers Thanks for reporting your issue!
Could you give me your GraphQL Schema and your configuration? I want to reproduce the issue.

**Comment by maoosi** [comment]
Experiencing the same issue - seems to be erroring on all GraphQL Enums.

Also it is not depending on the configuration (I've tried disabling everything else apart from `graphql-codegen-typescript-validation-schema` and the recommended scalars config).

Example Enum:

```gql
enum Allergen {
    MILK
    EGGS
    PEANUTS
    SOY
    WHEAT
    TREE_NUTS
    SHELLFISH
    FISH
    SESAME
}
```

**Comment by Code-Hex** [comment]
@maoosi I cannot reproduce this error

```gql
enum Allergen {
    MILK
    EGGS
    PEANUTS
    SOY
    WHEAT
    TREE_NUTS
    SHELLFISH
    FISH
    SESAME
}
```

then I can generate this code:

```ts
import { z } from 'zod'
import { Allergen } from '../types'

type Properties<T> = Required<{
  [K in keyof T]: z.ZodType<T[K], any, T[K]>;
}>;

type definedNonNullAny = {};

export const isDefinedNonNullAny = (v: any): v is definedNonNullAny => v !== undefined && v !== null;

export const definedNonNullAnySchema = z.any().refine((v) => isDefinedNonNullAny(v));

export const AllergenSchema = z.nativeEnum(Allergen);

```

and run `tsc --strict --noEmit example/zod/schemas.ts`

**Comment by paales** [comment]
Colleague of  @Giovanni-Schroevers here.

This schema gives me an error:

```graphql
input InputOne {
  field: InputNested!
}

input InputNested {
  field: String
}
```

If I make InputNested optional, it doesn't anymore. Debugging now.

**Comment by Code-Hex** [comment]
@paales mmm, I could generate validation schema w/o errors:

```ts
import { z } from 'zod'
import { InputOne, InputNested } from '../types'

type Properties<T> = Required<{
  [K in keyof T]: z.ZodType<T[K], any, T[K]>;
}>;

type definedNonNullAny = {};

export const isDefinedNonNullAny = (v: any): v is definedNonNullAny => v !== undefined && v !== null;

export const definedNonNullAnySchema = z.any().refine((v) => isDefinedNonNullAny(v));

export const InputOneSchema: z.ZodObject<Properties<InputOne>> = z.object({
    field: z.lazy(() => InputNestedSchema)
});

export const InputNestedSchema: z.ZodObject<Properties<InputNested>> = z.object({
    field: z.string().nullish()
});
```

Could you give me your configuration?

**Comment by paales** [comment]
Digging in the code it seems related to `notAllowEmptyString: true,`

**Comment by Code-Hex** [comment]
I'm wondering if it's the same as this quickstart.
https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema#quick-start

**Comment by paales** [comment]
If I remove `notAllowEmptyString: true,` it works as expected :) Not ideal, but good enough for now.

**Comment by Code-Hex** [comment]
@paales I'm sorry, I didn't read your latest comment, I could reproduce this error 🙏 
I will fix it ASAP

**Comment by paales** [comment]
Award for fastest responder in a GitHub issue goes to @Code-Hex! ❤️

**Comment by Code-Hex** [comment]
I just published the latest version as [v0.11.0](https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema/releases/tag/v0.11.0)

**Comment by maoosi** [comment]
Thanks @Code-Hex, sadly this did not fixed the issue on my end. Will try to provide a reproduction link in the coming days.

**Comment by maoosi** [comment]
@Code-Hex here is a reproduction link:
https://codesandbox.io/p/sandbox/mystifying-thompson-z2h8m9?welcome=true

Just run `pnpm run gen` to see the error:
✖ Cannot read properties of undefined (reading 'input')

Few notes:
- On my dev setup, I'm running a local GraphQL Yoga server and directly introspecting it via `http://127.0.0.1:4444/graphql`.
- Weirdly enough, I wasn’t able to reproduce the issue simply by manually re-creating the `schema.graphql` file. 
- What I had to do, is output a JSON introspection file of my local GraphQL Yoga endpoint using https://the-guild.dev/graphql/codegen/plugins/other/introspection and then use this file in the reproduction environment. This way I was able to reproduce the exact same error.

**Comment by Code-Hex** [comment]
@maoosi I understand why this is happening.

The generation logic relied on the schema passed from graphql-codegen. If this was a schema generated based on introspection, the astNode information was lost, so it seems that it was not possible to determine whether each schema was an enum or a scalar.

This issue was reported here:

https://github.com/graphql/graphql-js/issues/1575

I will fix the logic to take this into consideration 🙏

**Comment by Code-Hex** [comment]
I created a new issue https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema/issues/394
Close this issue one.

**Comment by maoosi** [comment]
Awesome, thanks for looking into it!
